class RecentFile {
  final String cid,
      poiId,
      name,
      poiType,
      union,
      thana,
      district,
      division,
      market,
      territory,
      area,
      region,
      zone,
      latLong;

  RecentFile(
      {required this.cid,
      required this.poiId,
      required this.name,
      required this.poiType,
      required this.union,
      required this.thana,
      required this.district,
      required this.division,
      required this.market,
      required this.territory,
      required this.area,
      required this.region,
      required this.zone,
      required this.latLong});
}

List demoRecentFiles = [
  RecentFile(
      cid: "1",
      poiId: "123",
      name: "Bristy",
      poiType: "cs",
      union: "Narisha",
      thana: "Barisal",
      district: "Dhaka",
      division: "dsd",
      market: "gf",
      territory: "bg",
      area: "mhj",
      region: "gh",
      zone: "qw",
      latLong: "ew"),
  RecentFile(
      cid: "2",
      poiId: "234",
      name: "Monir",
      poiType: "sc",
      union: "Raipara",
      thana: "Dhaka",
      district: "Dhaka",
      division: "op",
      market: "kj",
      territory: "mj",
      area: "mj",
      region: "nh",
      zone: "bg",
      latLong: "bg"),
  RecentFile(
      cid: "3",
      poiId: "345",
      name: "Hasan",
      poiType: "sc",
      union: "Narisha",
      thana: "Dhaka",
      district: "Dhaka",
      division: "tw",
      market: "dfsf",
      territory: "fggd",
      area: "hffg",
      region: "fgg",
      zone: "fgfg",
      latLong: "fgf"),
  RecentFile(
      cid: "4",
      poiId: "567",
      name: "Tahmina",
      poiType: "fg",
      union: "Raipara",
      thana: "Barisal",
      district: "Dhaka",
      division: "fg",
      market: "gf",
      territory: "gh",
      area: "hgh",
      region: "ds",
      zone: "ds",
      latLong: "rtt"),
  RecentFile(
      cid: "5",
      poiId: "678",
      name: "Lion",
      poiType: "jh",
      union: "Narisha",
      thana: "Sylhet",
      district: "Dhaka",
      division: "ty",
      market: "ty",
      territory: "hh",
      area: "qwq",
      region: "err",
      zone: "sa",
      latLong: "sd"),
  RecentFile(
      cid: "6",
      poiId: "987",
      name: "Fahim",
      poiType: "jg",
      union: "Sutarpara",
      thana: "Sylhet",
      district: "Dhaka",
      division: "dfdf",
      market: "gfdg",
      territory: "fgd",
      area: "fgdg",
      region: "gfg",
      zone: "dfgd",
      latLong: "hggh"),
  RecentFile(
      cid: "7",
      poiId: "62",
      name: "Hridoy",
      poiType: "df",
      union: "Narisha",
      thana: "Sylhet",
      district: "Dhaka",
      division: "dsd",
      market: "sdds",
      territory: "sdds",
      area: "sds",
      region: "sds",
      zone: "fdf",
      latLong: "fgfg"),
  RecentFile(
      cid: "8",
      poiId: "62",
      name: "Hridoy",
      poiType: "df",
      union: "Narisha",
      thana: "Sylhet",
      district: "Dhaka",
      division: "dsd",
      market: "sdds",
      territory: "sdds",
      area: "sds",
      region: "sds",
      zone: "fdf",
      latLong: "fgfg"),
  RecentFile(
      cid: "9",
      poiId: "62",
      name: "Hridoy",
      poiType: "df",
      union: "Narisha",
      thana: "Sylhet",
      district: "Dhaka",
      division: "dsd",
      market: "sdds",
      territory: "sdds",
      area: "sds",
      region: "sds",
      zone: "fdf",
      latLong: "fgfg"),
  RecentFile(
      cid: "7",
      poiId: "62",
      name: "Hridoy",
      poiType: "df",
      union: "Narisha",
      thana: "Sylhet",
      district: "Dhaka",
      division: "dsd",
      market: "sdds",
      territory: "sdds",
      area: "sds",
      region: "sds",
      zone: "fdf",
      latLong: "fgfg"),
  RecentFile(
      cid: "7",
      poiId: "62",
      name: "Hridoy",
      poiType: "df",
      union: "Narisha",
      thana: "Sylhet",
      district: "Dhaka",
      division: "dsd",
      market: "sdds",
      territory: "sdds",
      area: "sds",
      region: "sds",
      zone: "fdf",
      latLong: "fgfg"),
];
